name: Deploy on push
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  runs-on: ubuntu-latest
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ${{ env.runs-on }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: "package.json"

      # - name: Install Dependencies
      #   run: npm ci --production

      - name: Lint Code Base
        uses: super-linter/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"

      # - name: Test Code
      #   run: npm run test --coverage

      - name: Lint Commit Message
        uses: wagoid/commitlint-github-action@main

  deploy:
    name: Deploy
    runs-on: ${{ env.runs-on }}
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo a |
          echo "${{ toJson(vars) }}"
        name: ${{ env.NODE_VERSION }} ${{ env.TEST }}
        env:
          NODE_VERSION: ${{ steps.setup-node.outputs.node-version }}
