---
name: Deploy on push
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - run: ls -a

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: package.json

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      # - run: |
      #     echo "GIT_URL=$GITHUB_REPOSITORY" >> $GITHUB_ENV
      # - run: |
      #     echo "EEEEE\
      #     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
      #     BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\
      #     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
      # - run: |
      #     echo "Working variable from variable: $GIT_URL"
      #     echo ${GITHUB_REPOSITORY}
      - run: ls -a

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
