name: Deploy on push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@main

      - name: Setup ${{ env.NODE_VERSION }} Node.js
        id: setup-node
        uses: actions/setup-node@main
        with:
          node-version-file: "package.json"
        env:
          NODE_VERSION: ${{ steps.setup-node.outputs.node-version }}

      - run: |
          echo "${{ toJson(vars) }}"

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
